---
title: "p8105_hw3_nrl2142"
output: github_document
date: "2025-10-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library (ggridges)
library(patchwork)
library(p8105.datasets)
```
## Problem 1
```{r}
data("instacart")
instacart

instacart|>
  count(aisle_id, sort = TRUE)
```

There are `r n_distinct(instacart$aisle_id)` number of aisles in the instacart dataset. The aisles with the most items ordered from are aisles 83, 24, 123, 120, 21, 115, 84, 107, 91 and 112. 

Making a plot
```{r}
morethantenk_df =
instacart |>
  select(aisle_id)|>
  count(aisle_id, name = "n" ) |>
  filter (n>10000)|>
  arrange(desc(n))

morethantenk_df

ggplot(morethantenk_df, aes(x=n, y=factor(aisle_id))) +
  geom_col() +
  labs (x = "Count", 
        y = "Aisle ID",
        title = "Aisles with more than 10,000 Items")
```

Making a table
```{r}
targetaisles_df =
  instacart |>
  select (aisle, product_name)|>
  filter(aisle == c("baking ingredients", "dog food care", "packaged vegetables fruits")) |>
   group_by(product_name, aisle) |>
  summarise(item_count =n ())|>
  arrange (aisle, desc(item_count)) |>
  group_by(aisle) |>
  slice_max(product_name, n=3) |>
  drop_na() 

targetaisles_df
  
  
```
Making the 2x7 table 
```{r}

orderhour_df <- instacart |>
  select(product_name, order_hour_of_day, order_dow) |>
  filter(product_name == c("Pink Lady Apples", "Coffee Ice Cream")) |>
  group_by(product_name, order_dow) |>
  summarise(mean_value = mean(order_hour_of_day, na.rm = TRUE), .groups = "drop") |>
  mutate(order_dow = recode(as.character(order_dow),
                            `0` = "Sunday",
                            `1` = "Monday",
                            `2` = "Tuesday",
                            `3` = "Wednesday",
                            `4` = "Thursday",
                            `5` = "Friday",
                            `6` = "Saturday")) |>
  pivot_wider(
    names_from = order_dow,
    values_from = mean_value
  )
orderhour_df
```

